name: Multi-Dimensional Matrix Demo

on:
  workflow_dispatch:

jobs:
  echo-combinations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fruit: [apple, banana, mango]
        vegetable: [carrot, spinach]
        number: [1, 2]
        alphabet: [a, b, c, d, e, f, g, k, l, m, n, o, p, x, y, z]
    steps:
      - name: Echo Matrix Values
        run: |
          echo "Fruit: ${{ matrix.fruit }}"
          echo "Vegetable: ${{ matrix.vegetable }}"
          echo "Number: ${{ matrix.number }}"
          echo "Alphabet: ${{ matrix.alphabet }}"
